-- IT ARENA SUBJECT QUIZ v3
-- IMPORTANT: run this in a NEW Supabase PROJECT dedicated to this quiz.
-- Never put the service_role/secret key in the website.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text default '',
  email text default '',
  role text not null default 'student' check (role in ('student','admin')),
  warning_count integer not null default 0,
  blocked boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  category text not null,
  question text not null,
  option_a text not null,
  option_b text not null,
  option_c text not null,
  option_d text not null,
  correct_answer text not null check (upper(correct_answer) in ('A','B','C','D')),
  created_at timestamptz not null default now()
);

create table if not exists public.quiz_results (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  subject text not null,
  score integer not null default 0,
  total_questions integer not null default 0,
  percentage numeric not null default 0,
  completed_at timestamptz not null default now()
);

alter table public.profiles add column if not exists role text default 'student';
alter table public.profiles add column if not exists warning_count integer default 0;
alter table public.profiles add column if not exists blocked boolean default false;
alter table public.quiz_results add column if not exists subject text;
alter table public.quiz_results add column if not exists total_questions integer;
alter table public.quiz_results add column if not exists percentage numeric;
alter table public.quiz_results add column if not exists completed_at timestamptz default now();

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.profiles(id,name,email)
  values(new.id,coalesce(new.raw_user_meta_data->>'name',''),new.email)
  on conflict (id) do update set name=excluded.name,email=excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

-- Browser-safe profile creation/update for the currently authenticated user.
-- SECURITY DEFINER lets this run without requiring a direct INSERT/UPDATE policy.
create or replace function public.ensure_my_profile(profile_name text, profile_email text)
returns public.profiles
language plpgsql
security definer
set search_path=public
as $$
declare result public.profiles;
begin
  if auth.uid() is null then raise exception 'Not authenticated'; end if;
  insert into public.profiles(id,name,email,role)
  values(auth.uid(),coalesce(profile_name,''),coalesce(profile_email,''),'student')
  on conflict (id) do update
    set name=excluded.name, email=excluded.email
    where public.profiles.role <> 'admin';
  select * into result from public.profiles where id=auth.uid();
  return result;
end;
$$;

grant execute on function public.ensure_my_profile(text,text) to authenticated;

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles where id=auth.uid() and role='admin');
$$;

create or replace function public.record_quiz_warning()
returns jsonb language plpgsql security definer set search_path=public as $$
declare new_count integer; is_blocked boolean;
begin
  update public.profiles
  set warning_count=least(coalesce(warning_count,0)+1),
      blocked=(least(coalesce(warning_count,0)+1)>=3)
  where id=auth.uid() and role='student'
  returning warning_count,blocked into new_count,is_blocked;
  if new_count is null then raise exception 'Student profile not found'; end if;
  return jsonb_build_object('warning_count',new_count,'blocked',is_blocked);
end;
$$;

-- Public-to-authenticated leaderboard data without exposing student email addresses.
create or replace function public.get_leaderboard()
returns table(student_name text, subject text, score integer, total_questions integer, percentage numeric, completed_at timestamptz)
language sql stable security definer set search_path=public as $$
  select coalesce(p.name,'Student'), r.subject, r.score, r.total_questions, r.percentage, r.completed_at
  from public.quiz_results r
  left join public.profiles p on p.id=r.user_id
  order by r.percentage desc, r.completed_at asc;
$$;

-- Admin-only results including email.
create or replace function public.get_admin_results()
returns table(student_name text, email text, subject text, score integer, total_questions integer, percentage numeric, completed_at timestamptz)
language plpgsql stable security definer set search_path=public as $$
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  return query
  select coalesce(p.name,'Student'), coalesce(p.email,''), r.subject, r.score, r.total_questions, r.percentage, r.completed_at
  from public.quiz_results r
  left join public.profiles p on p.id=r.user_id
  order by r.completed_at desc;
end;
$$;

grant execute on function public.get_leaderboard() to authenticated;
grant execute on function public.get_admin_results() to authenticated;
grant execute on function public.record_quiz_warning() to authenticated;

alter table public.profiles enable row level security;
alter table public.questions enable row level security;
alter table public.quiz_results enable row level security;

-- Clean/recreate policies for repeatable setup.
drop policy if exists profiles_self_select on public.profiles;
drop policy if exists profiles_admin_select on public.profiles;
drop policy if exists profiles_self_insert on public.profiles;
drop policy if exists profiles_admin_update on public.profiles;
drop policy if exists questions_authenticated_select on public.questions;
drop policy if exists questions_admin_insert on public.questions;
drop policy if exists questions_admin_delete on public.questions;
drop policy if exists results_self_insert on public.quiz_results;
drop policy if exists results_self_select on public.quiz_results;
drop policy if exists results_admin_select on public.quiz_results;

create policy profiles_self_select on public.profiles for select to authenticated using (auth.uid()=id);
create policy profiles_admin_select on public.profiles for select to authenticated using (public.is_admin());
create policy profiles_self_insert on public.profiles for insert to authenticated with check (auth.uid()=id);
create policy profiles_admin_update on public.profiles for update to authenticated using (public.is_admin()) with check (public.is_admin());

create policy questions_authenticated_select on public.questions for select to authenticated using (true);
create policy questions_admin_insert on public.questions for insert to authenticated with check (public.is_admin());
create policy questions_admin_delete on public.questions for delete to authenticated using (public.is_admin());

create policy results_self_insert on public.quiz_results for insert to authenticated with check (auth.uid()=user_id);
create policy results_self_select on public.quiz_results for select to authenticated using (auth.uid()=user_id);
create policy results_admin_select on public.quiz_results for select to authenticated using (public.is_admin());

-- After registering your own account, run:
-- update public.profiles set role='admin' where email='YOUR_EMAIL';
